services:
  backend:
    build:
      context: ./backend
    container_name: stockboy-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - stockboy-data:/app/data
    env_file:
      - docker.env
    environment:
      - FLASK_APP=app.py
    restart: unless-stopped
    networks:
      - stockboy-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stockboy-frontend
    ports:
      - "3000:3000"
    env_file:
      - docker.env
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - stockboy-network

volumes:
  stockboy-data:


networks:
  stockboy-network:
    driver: bridge
